directories:
  output: release
  buildResources: build
appId: com.profact.app
productName: ProFact
executableName: ProFact
asar: true
files:
  - filter:
      - dist-react/**/*
      - electron/**/*
      - ../backend/**/*
      - public/profact-icone.ico
win:
  signAndEditExecutable: false
  target:
    - nsis
    - portable
  icon: public/profact-icone.ico
nsis:
  installerIcon: public/profact-icone.ico
  uninstallerIcon: public/profact-icone.ico
  license: license.txt
  oneClick: false
  perMachine: true
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: ProFact
  runAfterFinish: true
electronVersion: 22.3.27
